### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by AmandaS98** [Satriaana/Blog#12]
- [x] youtube video description
- [x] Github org description
- [x] description/correction/touchups for [weekly mentor guidling.md](https://github.com/Satriaana/Core/blob/main/Weekly%20Mentor%20Instruction%20Guideline.md)  

Update directly

**Comment by ChamodiePubudini** [comment]
Here is our description;
SATRIAANA is a community which is an independent and having a higher security level as an open source community. We are maintaining our  targets accurately in order to provide a meaningful output to the global citizen
