### ISSUE TITLE
Legal review of Net-neutrality article @AmandaS98

### ISSUE THREAD

**Issue by SenaliMadawala** [Satriaana/Blog#8]
Should complete the legal process of Net-neutrality article. (Please give a small statement about the legal side of this part through the [research sheet](https://nsbm365-my.sharepoint.com/:x:/g/personal/cpmsdissanayake_students_nsbm_lk/EdV9tOiYO-tMoCyRdO1WTpEBC8uA13Ps-KEeXuW_MUlOMA?e=It5jGa))
@AmandaS98

**Comment by AmandaS98** [comment]
Finished the legal review
